#include "engine/Game.h"
#include "deckz_config.h"
#include <iostream>
#include <fstream>
#include <sstream>
#include <cstdlib>
#include <cstdio>
#include <ctime>
#include <stdexcept>
#include <string>
#ifdef _WIN32
#include <process.h>
#else
#include <unistd.h>
#endif

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

static std::string readFile(const std::string& path) {
    std::ifstream f(path);
    if (!f.is_open()) throw std::runtime_error("Cannot open: " + path);
    return std::string(std::istreambuf_iterator<char>(f), {});
}

static std::string tempDir() {
    const char* tmp = std::getenv("TEMP");
    if (!tmp) tmp = std::getenv("TMP");
    if (!tmp) tmp = ".";
    std::string dir(tmp);
    for (char& c : dir) if (c == '\\') c = '/';
    return dir;
}

static std::string tempFilePath() {
    // Use PID + timestamp to avoid collisions across concurrent runs
    std::string name = "deckz_gen_"
        + std::to_string(std::time(nullptr))
        + "_" + std::to_string(
#ifdef _WIN32
            static_cast<int>(_getpid())
#else
            static_cast<int>(getpid())
#endif
        );
    return tempDir() + "/" + name + ".cpp";
}

static void validateConfig(const std::string& json) {
    // Dry-run: parse the config through the full engine to catch errors early
    engine::Game game;
    game.loadFromString(json);
    game.start();
}

static void generateMain(std::ostream& out, const std::string& json) {
    out << "// Auto-generated by deckz build — do not edit\n"
        << "#include \"engine/Game.h\"\n"
        << "#include \"ui/TerminalUI.h\"\n"
        << "#include <iostream>\n\n"
        << "static const char CONFIG_JSON[] = R\"DECKZ_CFG(\n"
        << json << "\n"
        << ")DECKZ_CFG\";\n\n"
        << "int main() {\n"
        << "    try {\n"
        << "        engine::Game game;\n"
        << "        game.loadFromString(CONFIG_JSON);\n"
        << "        game.start();\n"
        << "        ui::TerminalUI terminal(game);\n"
        << "        terminal.run();\n"
        << "    } catch (const std::exception& e) {\n"
        << "        std::cerr << \"Error: \" << e.what() << \"\\n\";\n"
        << "        return 1;\n"
        << "    }\n"
        << "    return 0;\n"
        << "}\n";
}

static void buildTui(const std::string& configPath, const std::string& outputPath) {
    // 1. Read config
    std::cout << "Reading config: " << configPath << "\n";
    std::string json = readFile(configPath);

    // 2. Validate
    std::cout << "Validating config...\n";
    validateConfig(json);

    // 3. Generate main.cpp into a temp file
    std::string tmpSrc = tempFilePath();
    {
        std::ofstream out(tmpSrc);
        if (!out.is_open()) throw std::runtime_error("Cannot write temp file: " + tmpSrc);
        generateMain(out, json);
    }

    // 4. Compile
    std::ostringstream cmd;
    cmd << "\"" << DECKZ_CXX_COMPILER << "\""
        << " -std=c++17"
        << " -I\"" << DECKZ_INCLUDE_DIR  << "\""
        << " -I\"" << DECKZ_NLOHMANN_DIR << "\""
        << " \"" << tmpSrc << "\""
        << " \"" << DECKZ_UI_LIB     << "\""
        << " \"" << DECKZ_ENGINE_LIB << "\""
        << " " << DECKZ_PLATFORM_LIBS
        << " -o \"" << outputPath << "\"";

    std::cout << "Compiling...\n";
    // On Windows, cmd.exe requires the whole command to be wrapped in quotes
    // when the executable path itself is quoted.
#ifdef _WIN32
    std::string shellCmd = "\"" + cmd.str() + "\"";
#else
    std::string shellCmd = cmd.str();
#endif
    int ret = std::system(shellCmd.c_str());

    std::remove(tmpSrc.c_str());

    if (ret != 0)
        throw std::runtime_error("Compilation failed (exit code " + std::to_string(ret) + ")");

    std::cout << "Built: " << outputPath << "\n";
}

static void validateTui(const std::string& configPath) {
    std::cout << "Reading config: " << configPath << "\n";
    std::string json = readFile(configPath);
    std::cout << "Validating...\n";
    validateConfig(json);
    std::cout << "OK\n";
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

static void printUsage() {
    std::cerr
        << "Usage:\n"
        << "  deckz build    --config <path> --output <path>\n"
        << "  deckz validate --config <path>\n\n"
        << "Options:\n"
        << "  -c, --config   Path to the game config JSON\n"
        << "  -o, --output   Output executable path (build only)\n"
        << "  -h, --help     Show this help\n";
}

int main(int argc, char* argv[]) {
    if (argc < 2) { printUsage(); return 1; }

    std::string sub = argv[1];
    if (sub == "--help" || sub == "-h") { printUsage(); return 0; }
    if (sub != "build" && sub != "validate") {
        std::cerr << "Unknown subcommand '" << sub << "'\n";
        printUsage();
        return 1;
    }

    std::string configPath, outputPath;

    for (int i = 2; i < argc; ++i) {
        std::string arg = argv[i];
        if ((arg == "--config" || arg == "-c") && i + 1 < argc)
            configPath = argv[++i];
        else if ((arg == "--output" || arg == "-o") && i + 1 < argc)
            outputPath = argv[++i];
        else if (arg == "--help" || arg == "-h") { printUsage(); return 0; }
        else {
            std::cerr << "Unknown argument: " << arg << "\n";
            printUsage();
            return 1;
        }
    }

    if (configPath.empty()) {
        std::cerr << "Error: --config is required\n\n";
        printUsage();
        return 1;
    }
    if (sub == "build" && outputPath.empty()) {
        std::cerr << "Error: --output is required for build\n\n";
        printUsage();
        return 1;
    }

    try {
        if (sub == "build")
            buildTui(configPath, outputPath);
        else
            validateTui(configPath);
    } catch (const std::exception& e) {
        std::cerr << "Error: " << e.what() << "\n";
        return 1;
    }

    return 0;
}
